

COURSE_NUMBERS = {
    17: "Wii Moo Moo Meadows",
}

COURSE_IDS = {
    27: "Mario Kart Stadium",
    28: "Water Park",
    19: "Sweet Sweet Canyon",
    17: "Thwomp Ruins",
    16: "Mario Circuit",
    18: "Toad Harbor",
    20: "Twisted Mansion",
    21: "Shy Guy Falls",
    26: "Sunshine Airport",
    29: "Dolphin Shoals",
    25: "Electrodrome",
    24: "Mount Wario",
    23: "Cloudtop Cruise",
    22: "Bone-Dry Dunes",
    30: "Bowser's Castle",
    31: "Rainbow Road",
    33: "Wii Moo Moo Meadows",
    38: "GBA Mario Circuit",
    36: "DS Cheep Cheep Beach",
    35: "N64 Toad's Turnpike",
    42: "GCN Dry Dry Desert",
    41: "SNES Donut Plains 3",
    34: "N64 Royal Raceway",
    32: "3DS DK Jungle",
    46: "DS Wario Stadium",
    37: "GCN Sherbet Land",
    39: "3DS Music Park",
    45: "N64 Yoshi Valley",
    44: "DS Tick-Tock Clock",
    43: "3DS Piranha Plant Slide",
    40: "Wii Grumble Volcano",
    47: "N64 Rainbow Road",
    56: "GCN Yoshi Circuit",
    53: "Excitebike Arena",
    50: "Dragon Driftway",
    49: "Mute City",
    57: "Wii Wario's Gold Mine",
    58: "SNES Rainbow Road",
    55: "Ice Ice Outpost",
    51: "Hyrule Circuit",
    61: "GCN Baby Park",
    62: "GBA Cheese Land",
    54: "Wild Woods",
    64: "Animal Crossing (Spring)",
    52: "Animal Crossing (Summer)",
    65: "Animal Crossing (Autumn)",
    66: "Animal Crossing (Winter)",
    60: "3DS Neo Bowser City",
    59: "GBA Ribbon Road",
    48: "Super Bell Subway",
    63: "Big Blue",
}

CHARACTERS = {
    3: ("Daisy", 3),
    4: ("Yoshi (Green)", 7),
    5: ("Toad", 16),
}

KARTS = {
    0: ("Standard Kart", 0),
    9: ("Buggybud", 132),
}

WHEELS = {
    0: ("Normal", 348),
    6: ("Button", 354),
}

GLIDERS = {
    0: ("Super Glider", 372),
    1: ("Cloud Glider", 432),
}

FLAGS = [
   (None, None),
   ("JP", 0),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   ("AI", 41),
   ("AG", 60),
   ("AR", 53),
   ("AW", 70),
   ("BS", 17),
   ("BB", 31),
   ("BZ", 46),
   ("BO", 64),
   ("BR", 10),
   ("VG", 25),
   ("CA", 39),
   ("KY", None),
   ("CL", 52),
   ("CO", 69),
   ("CR", 16),
   ("DM", 30),
   ("DO", 45),
   ("EC", 63),
   ("SV", 9),
   ("GF", None),
   ("GD", 38),
   ("GP", None),
   ("GT", 51),
   ("GY", 68),
   ("HT", 15),
   ("HN", 29),
   ("JM", 44),
   ("MQ", None),
   ("MX", 8),
   ("MS", 24),
   ("AN", 37),
   ("NI", 58),
   ("PA", 50),
   ("PY", 67),
   ("PE", 14),
   ("KN", 28),
   ("LC", 43),
   ("VC", 62),
   ("SR", 7),
   ("TT", 23),
   ("TC", 36),
   ("US", 57),
   ("UY", 49),
   ("VI", 66),
   ("VE", 13),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   ("AL", None),
   ("AU", 61),
   ("AT", 6),
   ("BE", 22),
   ("BA", None),
   ("BW", None),
   ("BG", 48),
   ("HR", 65),
   ("CY", 12),
   ("CZ", 27),
   ("DK", 42),
   ("EE", None),
   ("FI", 5),
   ("FR", 21),
   ("DE", 35),
   ("GR", 56),
   ("HU", 47),
   ("IS", None),
   ("IE", 11),
   ("IT", 26),
   ("LV", None),
   ("LS", None),
   ("LI", None),
   ("LT", None),
   ("LU", 33),
   ("MK", None),
   ("MT", None),
   ("ME", None),
   ("MZ", None),
   ("NA", None),
   ("NL", 40),
   ("NZ", 59),
   ("NO", 2),
   ("PL", 20),
   ("PT", 32),
   ("RO", 55),
   ("RU", 4),
   ("RS", None),
   ("SK", 34),
   ("SI", None),
   ("ZA", None),
   ("ES", 19),
   ("SZ", None),
   ("SE", 54),
   ("CH", 1),
   ("TR", 18),
   ("GB", 3),
   ("ZM", None),
   ("ZW", None),
   ("AZ", None),
   ("MR", None),
   ("ML", None),
   ("NE", None),
   ("TD", None),
   ("SD", None),
   ("ER", None),
   ("DJ", None),
   ("SO", None),
   ("AD", None),
   ("GI", None),
   ("GG", None),
   ("IM", None),
   ("JE", None),
   ("MC", None),
   ("TW", None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   ("KR", None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   ("HK", None),
   ("MO", None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   ("ID", None),
   ("SG", None),
   ("TH", None),
   ("PH", None),
   ("MY", None),
   (None, None),
   (None, None),
   (None, None),
   ("CN", None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   ("AE", None),
   (None, None),
   ("EG", None),
   ("OM", None),
   ("QA", None),
   ("KW", None),
   ("SA", None),
   ("SY", None),
   ("BH", None),
   ("JO", None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   ("SM", None),
   ("VA", None),
   ("BM", None),
   ("IN", None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   ("NG", None),
   ("AO", None),
   ("GH", None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
   (None, None),
]
